"""Migracion inicial Fase 1 Kardex

Revision ID: 51135cb4d5f7
Revises: 
Create Date: 2026-05-19 13:19:21.407168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51135cb4d5f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piezas_fisicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=False),
    sa.Column('catalogo_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('costo_ingreso', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catalogo_id'], ['catalogo_productos.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_interno')
    )
    op.create_table('movimientos_kardex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pieza_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('sede_origen_id', sa.Integer(), nullable=True),
    sa.Column('sede_destino_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pieza_id'], ['piezas_fisicas.id'], ),
    sa.ForeignKeyConstraint(['sede_destino_id'], ['sedes.id'], ),
    sa.ForeignKeyConstraint(['sede_origen_id'], ['sedes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # --- COMENTADO PARA PROTEGER TUS TABLAS ANTIGUAS ---
    # op.drop_table('playing_with_neon')
    # with op.batch_alter_table('ventas', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_ventas_vendedor'))
    # op.drop_table('ventas')
    # op.drop_table('logistica_externa')
    # op.drop_table('fotos_creaciones')
    # op.drop_table('maestro_bases_comedor')
    # op.drop_table('proveedores')
    # op.drop_table('sugerencias_insumos')
    # op.drop_table('maestro_telas')
    # with op.batch_alter_table('items_venta', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_items_venta'))
    # op.drop_table('items_venta')
    # op.drop_table('maestro_sillas')
    # op.drop_table('inventario_insumos')
    # with op.batch_alter_table('tickets_produccion', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_tickets_area'))
    #     batch_op.drop_index(batch_op.f('idx_tickets_estado'))
    #     batch_op.drop_index(batch_op.f('idx_tickets_item'))
    # op.drop_table('tickets_produccion')
    # op.drop_table('creaciones_vendedores')
    # op.drop_table('maestro_disenos_cojin')
    # op.drop_table('maestro_bases')
    # op.drop_table('recetas_muebles')
    # op.drop_table('maestro_tableros')
    # op.drop_table('maestro_butacas')
    # ---------------------------------------------------

    with op.batch_alter_table('catalogo_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=150), nullable=True))
        batch_op.alter_column('tipo_producto',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True, # <-- Cambiado a True
               existing_server_default=sa.text("'unitario'::character varying"))
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=50),
               nullable=True) # <-- Cambiado a True
        
        # --- COMENTADO PARA PROTEGER TUS COLUMNAS ANTIGUAS ---
        # batch_op.drop_column('en_stock')
        # batch_op.drop_column('precio_base')
        # batch_op.drop_column('origen_produccion')
        # batch_op.drop_column('foto_url')
        # batch_op.drop_column('requiere_tela')
        # batch_op.drop_column('requiere_madera')
        # batch_op.drop_column('nombre_modelo')
        # batch_op.drop_column('requiere_superficie')
        # batch_op.drop_column('es_plantilla')
        # batch_op.drop_column('stock_cantidad')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sede_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'sedes', ['sede_id'], ['id'])
        
        # --- COMENTADO PARA PROTEGER TUS COLUMNAS ANTIGUAS ---
        # batch_op.drop_column('empresa_ruc')
        # batch_op.drop_column('empresa_nombre')
        # batch_op.drop_column('area_asignada')
        # batch_op.drop_column('contrasena')
        # batch_op.drop_column('pin_acceso')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_acceso', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contrasena', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('area_asignada', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('empresa_nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('empresa_ruc', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('estado')
        batch_op.drop_column('sede_id')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('catalogo_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_cantidad', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('es_plantilla', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requiere_superficie', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre_modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('requiere_madera', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requiere_tela', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('origen_produccion', sa.VARCHAR(length=50), server_default=sa.text("'Interno'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('precio_base', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('en_stock', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('tipo_producto',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unitario'::character varying"))
        batch_op.drop_column('nombre')

    op.create_table('maestro_butacas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('material', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color_estructura', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Disponible'::character varying"), autoincrement=False, nullable=True),
    sa.Column('origen_produccion', sa.TEXT(), server_default=sa.text("'Interno'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('maestro_butacas_pkey')),
    sa.UniqueConstraint('sku', name=op.f('maestro_butacas_sku_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('maestro_tableros',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('material_base', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nombre_modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color_veta', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('acabado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Disponible'::character varying"), autoincrement=False, nullable=True),
    sa.Column('origen_produccion', sa.TEXT(), server_default=sa.text("'Externo'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('maestro_tableros_pkey')),
    sa.UniqueConstraint('sku', name=op.f('maestro_tableros_sku_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('recetas_muebles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('insumo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cantidad_necesaria', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['inventario_insumos.id'], name=op.f('recetas_muebles_insumo_id_fkey')),
    sa.ForeignKeyConstraint(['producto_id'], ['catalogo_productos.id'], name=op.f('recetas_muebles_producto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recetas_muebles_pkey'))
    )
    op.create_table('maestro_bases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('medida_altura', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Disponible'::character varying"), autoincrement=False, nullable=True),
    sa.Column('origen_produccion', sa.TEXT(), server_default=sa.text("'Interno'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('maestro_bases_pkey')),
    sa.UniqueConstraint('sku', name=op.f('maestro_bases_sku_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('maestro_disenos_cojin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nombre_diseno', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('tipo_tela', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('origen_produccion', sa.TEXT(), server_default=sa.text("'Interno'::text"), autoincrement=False, nullable=True),
    sa.Column('estado', sa.TEXT(), server_default=sa.text("'Disponible'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('maestro_disenos_cojin_pkey')),
    sa.UniqueConstraint('sku', name=op.f('maestro_disenos_cojin_sku_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('creaciones_vendedores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre_modelo', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('detalles_tecnicos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notas_casqueria', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('aprobado_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], name=op.f('creaciones_vendedores_vendedor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('creaciones_vendedores_pkey'))
    )
    op.create_table('tickets_produccion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('area_trabajo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('estado_ticket', sa.VARCHAR(length=50), server_default=sa.text("'Pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.Column('trabajador_asignado_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('foto_evidencia_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etapa', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('foto_evidencia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ticket_details_override', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items_venta.id'], name=op.f('tickets_produccion_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trabajador_asignado_id'], ['usuarios.id'], name=op.f('tickets_produccion_trabajador_asignado_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tickets_produccion_pkey'))
    )
    with op.batch_alter_table('tickets_produccion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tickets_item'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_tickets_estado'), ['estado_ticket'], unique=False)
        batch_op.create_index(batch_op.f('idx_tickets_area'), ['area_trabajo'], unique=False)

    op.create_table('inventario_insumos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_insumo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tipo_medida', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cantidad_actual', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inventario_insumos_pkey'))
    )
    op.create_table('maestro_sillas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color_estructura', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('origen_produccion', sa.TEXT(), server_default=sa.text("'Interno'::text"), autoincrement=False, nullable=True),
    sa.Column('estado', sa.TEXT(), server_default=sa.text("'Disponible'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('maestro_sillas_pkey')),
    sa.UniqueConstraint('sku', name=op.f('maestro_sillas_sku_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('items_venta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('producto', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('color_tela', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado_item', sa.VARCHAR(length=50), server_default=sa.text("'Pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('items_venta_venta_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('items_venta_pkey'))
    )
    with op.batch_alter_table('items_venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_items_venta'), ['venta_id'], unique=False)

    op.create_table('maestro_telas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('proveedor', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('coleccion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Disponible'::character varying"), autoincrement=False, nullable=True),
    sa.Column('origen_produccion', sa.TEXT(), server_default=sa.text("'Externo'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('maestro_telas_pkey')),
    sa.UniqueConstraint('sku', name=op.f('maestro_telas_sku_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('sugerencias_insumos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.TEXT(), server_default=sa.text("'General'::text"), autoincrement=False, nullable=True),
    sa.Column('foto_ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.TEXT(), server_default=sa.text("'Pendiente'::text"), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('datos_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sugerencias_insumos_pkey'))
    )
    op.create_table('proveedores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('especialidad', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('correo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('proveedores_pkey'))
    )
    op.create_table('maestro_bases_comedor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'Disponible'::character varying"), autoincrement=False, nullable=True),
    sa.Column('origen_produccion', sa.TEXT(), server_default=sa.text("'Interno'::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('maestro_bases_comedor_pkey')),
    sa.UniqueConstraint('sku', name=op.f('maestro_bases_comedor_sku_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('fotos_creaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creacion_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_subida', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creacion_id'], ['creaciones_vendedores.id'], name=op.f('fotos_creaciones_creacion_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('fotos_creaciones_pkey'))
    )
    op.create_table('logistica_externa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('insumo_nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('proveedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio_cotizado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fecha_entrega_proveedor', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'POR_PEDIR'::character varying"), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('logistica_externa_proveedor_id_fkey')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('logistica_externa_venta_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('logistica_externa_pkey'))
    )
    op.create_table('ventas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo_venta', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nombre_cliente', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dni_cliente', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('estado_general', sa.VARCHAR(length=50), server_default=sa.text("'En Producción'::character varying"), autoincrement=False, nullable=True),
    sa.Column('vendedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_emision', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.Column('fecha_entrega', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('celular_cliente', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('direccion_cliente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_pago', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('monto_adelanto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('monto_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('empresa_ruc', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('vendedor_nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tipo_documento', sa.VARCHAR(length=20), server_default=sa.text("'DNI'::character varying"), autoincrement=False, nullable=True),
    sa.Column('empresa_pago', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], name=op.f('ventas_vendedor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ventas_pkey')),
    sa.UniqueConstraint('codigo_venta', name=op.f('ventas_codigo_venta_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ventas_vendedor'), ['vendedor_id'], unique=False)

    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_table('movimientos_kardex')
    op.drop_table('piezas_fisicas')
    op.drop_table('sedes')
    # ### end Alembic commands ###
